language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  # Install deependancies
  - composer install --dev --prefer-dist

script:
  # Run the test
  - php ./vendor/phpunit/phpunit/phpunit --coverage-clover=build/logs/clover.xml

after_script:
  # Upload code coverage to Scrutinizr.com
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

  # Upload code coverage to Coveralls.io
  - php ./vendor/bin/coveralls -v

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
